function Invoke-LinkLocalMetadata {
    param([string]$Path,[hashtable]$Headers=@{},[ValidateSet('GET','PUT')][string]$Method='GET')
    if(-not$script:Context.IncludeNetwork){throw 'Metadata requests require network opt-in.'}
    if(-not$Path.StartsWith('/')-or$Path.StartsWith('//')-or$Path-match'[\r\n]'){throw 'Invalid metadata path.'}
    $request=[Net.HttpWebRequest]::Create('http://169.254.169.254'+$Path)
    $request.Proxy=$null;$request.AllowAutoRedirect=$false;$request.UseDefaultCredentials=$false;$request.Timeout=[Math]::Min(3000,$script:Context.CommandTimeoutSeconds*1000);$request.ReadWriteTimeout=$request.Timeout;$request.Method=$Method
    foreach($name in $Headers.Keys){$request.Headers[$name]=$Headers[$name]}
    if($Method-eq'PUT'){$request.ContentLength=0}
    $response=$null;$reader=$null
    try{$response=$request.GetResponse();$reader=New-Object IO.StreamReader($response.GetResponseStream());$buffer=New-Object char[] 65537;$count=0;while($count-lt$buffer.Length){$read=$reader.Read($buffer,$count,$buffer.Length-$count);if(-not$read){break};$count+=$read};if($count-ge$buffer.Length){throw 'Metadata response exceeds limit.'};return [string]::new($buffer,0,$count)}
    finally{if($reader){$reader.Dispose()};if($response){$response.Dispose()};$request.Abort()}
}
function Invoke-CloudAndToolsCheck {
    param([int]$Id)
    if($Id-eq140){
        $data=Get-ReferenceDocument (Join-Path $script:ModuleRoot '../data/reference/lolbas.json') 'LOLBAS'
        if($data){foreach($entry in Get-Limited @($data.Entries)){foreach($path in $entry.Paths){$expanded=[Environment]::ExpandEnvironmentVariables($path);if($expanded-match'(?i)^C:\\Windows\\'){$expanded=$env:SystemRoot+$expanded.Substring(10)};if($expanded-notmatch'[<>*?]' -and (Get-FilePresence $expanded)-eq'Present'){Add-Artifact $expanded 'LOLBAS catalog binary/library/script';Add-WritablePath $expanded 'Writable catalogued Windows executable/library/script.'}}}}
        foreach($key in Get-RegistryChildren 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Lxss'){Add-RegistryEvidence $key.PSPath @('DistributionName','BasePath','Version','DefaultUid');$base=Read-Registry $key.PSPath 'BasePath';if($base.State-eq'Present'){foreach($file in Get-BoundedFiles @($base.Value) -Depth 1 -Pattern '\.vhdx$|^passwd$|^shadow$'){Add-ReadableArtifact $file.FullName 'WSL Linux filesystem artifact; filesystem not mounted'}}}
        foreach($profile in Get-ProfileRoots){Add-Artifact (Join-Path $profile '.wslconfig') 'WSL configuration';foreach($name in @('.bash_history','.zsh_history','.ssh\config')){Add-Artifact (Join-Path $profile $name) 'Linux-shell artifact'}}
        return
    }
    Invoke-InventoryCheck 148
    foreach($key in @('HKLM:\SOFTWARE\Google\GCPW','HKLM:\SOFTWARE\Google\Google Accounts','HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\CDJ\AAD','HKLM:\SYSTEM\CurrentControlSet\Control\ContainerType')){Add-RegistryEvidence $key @('DomainJoinState','TenantId','CloudDomainJoin','ContainerType');foreach($child in Get-RegistryChildren $key){Add-Evidence $child.Name 'Cloud join/credential provider/container registry artifact.'}}
    try{$status=Invoke-ReadOnlyCommand "$env:SystemRoot\System32\dsregcmd.exe" '/status';foreach($line in $status-split'\r?\n'){if($line-match'^\s*(AzureAdJoined|EnterpriseJoined|DomainJoined|WorkplaceJoined|AzureAdPrt)\s*:\s*(YES|NO)\s*$'){Add-Evidence $Matches[1] 'Windows cloud/domain join and primary-refresh-token presence.' @{State=$Matches[2]}}}}catch{Set-CheckPartial 'Cloud join state command unavailable.' -ErrorRecord $_}
    if(-not$script:Context.IncludeNetwork){Set-CheckPartial 'Cloud metadata accessibility requires -IncludeNetwork; token exposure additionally requires -IncludeSensitive.';return}
    try{$metadata=Invoke-LinkLocalMetadata '/metadata/instance?api-version=2021-02-01' @{Metadata='true'}|ConvertFrom-Json;Add-Evidence 'Azure IMDS' 'Azure instance metadata is accessible to the current process.' @{Accessible=$true;Location=$metadata.compute.location;VmSize=$metadata.compute.vmSize};if($script:Context.IncludeSensitive){$token=Invoke-LinkLocalMetadata '/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F' @{Metadata='true'}|ConvertFrom-Json;Add-Evidence 'Azure managed identity' 'Managed-identity token endpoint accessibility; token discarded.' @{TokenReturned=([bool]$token.access_token);ExpiresOn=$token.expires_on;Value='[REDACTED]'} 'Low';$token=$null}}catch{Add-Evidence 'Azure IMDS' 'Metadata/identity request did not complete; absence, access denial and network filtering are not distinguished.' @{Accessible=$false}}
    try{$token=Invoke-LinkLocalMetadata '/latest/api/token' @{'X-aws-ec2-metadata-token-ttl-seconds'='60'} 'PUT';$headers=@{'X-aws-ec2-metadata-token'=$token};$instance=Invoke-LinkLocalMetadata '/latest/meta-data/instance-id' $headers;Add-Evidence 'AWS IMDSv2' 'AWS metadata session established.' @{Accessible=(-not[string]::IsNullOrWhiteSpace($instance))};if($script:Context.IncludeSensitive){$roles=Invoke-LinkLocalMetadata '/latest/meta-data/iam/security-credentials/' $headers;foreach($role in ($roles-split'\r?\n'|Where-Object{$_-match'^[A-Za-z0-9+=,.@_-]{1,128}$'}|Select-Object -First 1)){$credential=Invoke-LinkLocalMetadata ('/latest/meta-data/iam/security-credentials/'+[Uri]::EscapeDataString($role)) $headers|ConvertFrom-Json;Add-Evidence 'AWS instance role' 'Instance-role credential endpoint accessibility; values discarded.' @{CredentialsReturned=([bool]$credential.AccessKeyId-and[bool]$credential.SecretAccessKey);Expiration=$credential.Expiration;Value='[REDACTED]'} 'Low';$credential=$null}};$token=$null;$headers.Clear()}catch{Add-Evidence 'AWS IMDSv2' 'Metadata/role request did not complete; absence, access denial and filtering are not distinguished.' @{Accessible=$false}}
    try{$instance=Invoke-LinkLocalMetadata '/computeMetadata/v1/instance/id' @{'Metadata-Flavor'='Google'};Add-Evidence 'Google metadata' 'Google instance metadata accessibility.' @{Accessible=(-not[string]::IsNullOrWhiteSpace($instance))};if($script:Context.IncludeSensitive){$token=Invoke-LinkLocalMetadata '/computeMetadata/v1/instance/service-accounts/default/token' @{'Metadata-Flavor'='Google'}|ConvertFrom-Json;Add-Evidence 'Google service identity' 'Service-identity access-token endpoint accessibility; token discarded.' @{TokenReturned=([bool]$token.access_token);ExpiresIn=$token.expires_in;Value='[REDACTED]'} 'Low';$token=$null}}catch{Add-Evidence 'Google metadata' 'Metadata/identity request did not complete; absence, access denial and filtering are not distinguished.' @{Accessible=$false}}
}
